### assignment 2 R Programming

makeCacheMatrix <- function(x = matrix()) {
  
  # this function creates a special matrix object that can cache its inverse
  # this is useful to speed up computations if the matrix object is reused
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


cacheSolve <- function(x, ...) {
  # cacheSolve solves the inverse of a cache matrix object generated by 
  # the function MakeCacheMatrix
  
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}